workflows:
  ios-unsigned-build:
    name: iOS Unsigned IPA
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Install Pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Build iOS .app (No Code Signing)
        script: |
          # 1. Build the raw .app bundle without signing
          flutter build ios --release --no-codesign
          
          # 2. Convert the .app to an .ipa manually
          # (Flutter build ipa requires signing, so we do this manually)
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r -y payload.ipa Payload/
          
          # 3. Move the IPA to the export directory
          mv payload.ipa $CM_EXPORT_DIR/bite_flutter_unsigned.ipa
          
    artifacts:
      - bite_flutter_unsigned.ipa