workflows:
  ios-unsigned-ipa:
    name: iOS Unsigned IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install Pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Build and Package IPA
        script: |
          # 1. Build the .app bundle (unsigned)
          flutter build ios --release --no-codesign

          # 2. Navigate to the build directory
          cd build/ios/iphoneos

          # 3. Create the Payload folder structure required by Apple
          mkdir Payload
          mv Runner.app Payload/

          # 4. Zip the Payload folder into a .ipa file
          # The -y flag preserves symbolic links (crucial for iOS apps)
          zip -r -y bite_flutter.ipa Payload/

          # 5. Move the finished .ipa to the export directory
          mv bite_flutter.ipa $CM_EXPORT_DIR/bite_flutter.ipa

    artifacts:
      - bite_flutter.ipa # This ensures you download the .ipa file directly