workflows:
  ios-unsigned-build:
    name: iOS Unsigned IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Install Pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Build iOS without signing
        script: |
          # Build the .app bundle in release mode without code signing
          flutter build ios --release --no-codesign

      - name: Package .app into unsigned .ipa
        script: |
          # Navigate to the build output directory
          cd build/ios/iphoneos
          
          # Create the required Payload directory structure for an IPA
          mkdir Payload
          
          # Move the Runner.app into the Payload directory
          mv Runner.app Payload/
          
          # Zip the Payload directory into a .ipa file
          zip -r ios_unsigned.ipa Payload
          
          # Move the ipa back to the root or a known path for artifacts
          mv ios_unsigned.ipa $CM_EXPORT_DIR/ios_unsigned.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa  # Save the generated IPA so you can download it
    
    publishing:
      email:
        recipients:
          - tommypeyei@gmail.com # You will receive the download link here