workflows:
  ios-unsigned-build:
    name: iOS Unsigned IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean up and Setup
        script: |
          # 1. Clean Flutter
          flutter clean
          
          # 2. Delete old iOS dependency locks to force an update to iOS 15.5
          rm -f ios/Podfile.lock
          
          # 3. Get Flutter packages
          flutter pub get

      - name: Install Pods with Repo Update
        script: |
          # We run repo-update to ensure we get the latest Firebase specs
          find . -name "Podfile" -execdir pod install --repo-update \;

      - name: Build iOS without signing
        script: |
          # Build the .app bundle in release mode without code signing
          flutter build ios --release --no-codesign

      - name: Package .app into unsigned .ipa
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r ios_unsigned.ipa Payload
          mv ios_unsigned.ipa $CM_EXPORT_DIR/ios_unsigned.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
    
    publishing:
      email:
        recipients:
          - tommypeyei@gmail.com