// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFyXUto8rG_s9Or_WxBSxqKs0ak_zCh0w',
    appId: '1:286483797129:web:4d04d1fa651a0636ac2258',
    messagingSenderId: '286483797129',
    projectId: 'bite-35e1a',
    authDomain: 'bite-35e1a.firebaseapp.com',
    databaseURL: 'https://bite-35e1a-default-rtdb.firebaseio.com',
    storageBucket: 'bite-35e1a.firebasestorage.app',
    measurementId: 'G-B1TT864DF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD43b5PBy_jE10hLhYRQI-hNokeFVpOY_4',
    appId: '1:286483797129:android:53f1159ef0d90d14ac2258',
    messagingSenderId: '286483797129',
    projectId: 'bite-35e1a',
    databaseURL: 'https://bite-35e1a-default-rtdb.firebaseio.com',
    storageBucket: 'bite-35e1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Fd9pmv6phMPfqSz79gDdc-LwBX-wKnI',
    appId: '1:286483797129:ios:703aee05eca84577ac2258',
    messagingSenderId: '286483797129',
    projectId: 'bite-35e1a',
    databaseURL: 'https://bite-35e1a-default-rtdb.firebaseio.com',
    storageBucket: 'bite-35e1a.firebasestorage.app',
    iosBundleId: 'com.example.biteFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Fd9pmv6phMPfqSz79gDdc-LwBX-wKnI',
    appId: '1:286483797129:ios:703aee05eca84577ac2258',
    messagingSenderId: '286483797129',
    projectId: 'bite-35e1a',
    databaseURL: 'https://bite-35e1a-default-rtdb.firebaseio.com',
    storageBucket: 'bite-35e1a.firebasestorage.app',
    iosBundleId: 'com.example.biteFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFyXUto8rG_s9Or_WxBSxqKs0ak_zCh0w',
    appId: '1:286483797129:web:c483c897787fc189ac2258',
    messagingSenderId: '286483797129',
    projectId: 'bite-35e1a',
    authDomain: 'bite-35e1a.firebaseapp.com',
    databaseURL: 'https://bite-35e1a-default-rtdb.firebaseio.com',
    storageBucket: 'bite-35e1a.firebasestorage.app',
    measurementId: 'G-C0MXKG6RDB',
  );
}
